services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wanderlust-frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wanderlust-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped