# ===============================================
# Stage 1: Install dependencies and  run tests
# ===============================================

FROM node:22-bookworm-slim AS backend-builder

# Set the working directory to /app
WORKDIR /app

# copy dependency files
COPY package*.json ./

# Install dependencies
RUN npm install

#Copy the application source code 
COPY . .

# RUN tests
RUN npm test

# ===============================================
# Stage 2: Production Node.js server    
# ===============================================

FROM node:22-bookworm-slim AS backend-production

# Set the working directory to /app
WORKDIR /app

# Tell Node to run in production mode
ENV NODE_ENV=production

# Copy dependecy files
COPY package*.json ./

# Install production dependencies only  
RUN npm install --omit=dev \
    && npm cache clean --force

# Copy application source from builder
COPY --from=backend-builder /app ./

# Run application as non-root user
USER node

# Expose port 3000 for the  backend
EXPOSE 3000

# Start backend
CMD ["node", "start"]